Problem 4.1: Array Creation

In [1]:
import numpy as np
import time

# Problem 1: Array Creation

# 1. Initialize an empty array with size 2X2.
empty_2x2 = np.empty((2, 2))
print("1) Empty 2x2 array:\n", empty_2x2, "\n")

# 2. Initialize an all one array with size 4X2.
ones_4x2 = np.ones((4, 2))
print("2) Ones 4x2 array:\n", ones_4x2, "\n")

# 3. Return a new array of given shape and type, filled with fill value.
# Example: shape (3,3), fill value = 7
full_array = np.full((3, 3), 7)
print("3) Full array 3x3 filled with 7:\n", full_array, "\n")

# 4. Return a new array of zeros with same shape and type as a given array.
given = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_given = np.zeros_like(given)
print("4) Zeros like given array:\n", zeros_like_given, "\n")

# 5. Return a new array of ones with same shape and type as a given array.
ones_like_given = np.ones_like(given)
print("5) Ones like given array:\n", ones_like_given, "\n")

# 6. Convert list new_list = [1,2,3,4] to numpy array.
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("6) Array from list:", arr_from_list)


1) Empty 2x2 array:
 [[5.97305850e-316 0.00000000e+000]
 [5.31410685e-317 6.82334986e-310]] 

2) Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3) Full array 3x3 filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

4) Zeros like given array:
 [[0 0 0]
 [0 0 0]] 

5) Ones like given array:
 [[1 1 1]
 [1 1 1]] 

6) Array from list: [1 2 3 4]


Problem 2: Array Manipulation — Ranges & Indexing

In [2]:
# Problem 2: Array Manipulation

# 1. Create an array with values ranging from 10 to 49.
arr_10_49 = np.arange(10, 50)
print("1) 10 to 49:\n", arr_10_49, "\n")

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
mat_0_8 = np.arange(9).reshape(3, 3)
print("2) 3x3 matrix 0..8:\n", mat_0_8, "\n")

# 3. Create a 3X3 identity matrix.
identity_3 = np.eye(3)
print("3) Identity 3x3:\n", identity_3, "\n")

# 4. Create a random array of size 30 and find mean.
rand_30 = np.random.random(30)
mean_30 = rand_30.mean()
print("4) Random 30 mean:", mean_30, "\n")

# 5. Create 10X10 random array and find min/max.
rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("5) Min:", min_val, " Max:", max_val, "\n")

# 6. Create zero array size 10 and replace 5th element with 1.
zero_10 = np.zeros(10)
zero_10[4] = 1  # 5th element index = 4
print("6) Zero array with 5th element=1:\n", zero_10, "\n")

# 7. Reverse arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("7) Reversed array:\n", reversed_arr, "\n")

# 8. Create a 2D array with 1 on border and 0 inside.
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("8) Border 1, inside 0:\n", border, "\n")

# 9. Create 8X8 checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9) Checkerboard 8x8:\n", checkerboard)


1) 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2) 3x3 matrix 0..8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3) Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4) Random 30 mean: 0.4644875329056558 

5) Min: 0.01497000509336921  Max: 0.9992821000673514 

6) Zero array with 5th element=1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

7) Reversed array:
 [0 4 0 0 2 1] 

8) Border 1, inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 

9) Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3: Array Operations

In [4]:
# Problem 3: Array Operations

x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add x and y.
add_xy = x + y
print("1) x + y:\n", add_xy, "\n")

# 2. Subtract x and y.
sub_xy = x - y
print("2) x - y:\n", sub_xy, "\n")

# 3. Multiply array with integer of choice (say 3).
mul_x = x * 3
print("3) x * 3:\n", mul_x, "\n")

# 4. Square of each element.
square_x = x ** 2
print("4) x squared:\n", square_x, "\n")

# 5. Dot products:
dot_vw = np.dot(v, w)      # scalar
dot_xv = np.dot(x, v)      # result shape (2,)
dot_xy = np.dot(x, y)      # result shape (2,2)

print("5a) v · w =", dot_vw)
print("5b) x · v =", dot_xv)
print("5c) x · y:\n", dot_xy, "\n")

# 6. Concatenate:
# x and y along rows (axis=0)
concat_xy_rows = np.concatenate((x, y), axis=0)

# v and w along columns => make them column vectors first
concat_vw_cols = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("6a) concat x & y along rows:\n", concat_xy_rows)
print("6b) concat v & w along columns:\n", concat_vw_cols, "\n")

# 7. Concatenate x and v and explain error.
try:
    concat_xv = np.concatenate((x, v))
    print("7) concat(x, v):\n", concat_xv)
except Exception as e:
    print("7) concat(x, v) ERROR because shapes differ.")
    print("   x shape:", x.shape, " (2D)")
    print("   v shape:", v.shape, " (1D)")
    print("   Error:", e)


1) x + y:
 [[ 6  8]
 [10 13]] 

2) x - y:
 [[-4 -4]
 [-4 -3]] 

3) x * 3:
 [[ 3  6]
 [ 9 15]] 

4) x squared:
 [[ 1  4]
 [ 9 25]] 

5a) v · w = 219
5b) x · v = [29 77]
5c) x · y:
 [[19 22]
 [50 58]] 

6a) concat x & y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b) concat v & w along columns:
 [[ 9 11]
 [10 12]] 

7) concat(x, v) ERROR because shapes differ.
   x shape: (2, 2)  (2D)
   v shape: (2,)  (1D)
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4: Matrix Operations + Linear System

In [5]:
# Problem 4: Matrix Operations

A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
proof_identity = A @ A_inv
print("1) A @ inv(A):\n", proof_identity, "\n")  # should be close to identity

# 2. Prove AB != BA
AB = A @ B
BA = B @ A
print("2) AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA ?", np.allclose(AB, BA), "\n")

# 3. Prove (AB)^T = B^T A^T
lhs = (AB).T
rhs = B.T @ A.T
print("3) (AB)^T:\n", lhs)
print("   B^T A^T:\n", rhs)
print("   Equal ?", np.allclose(lhs, rhs), "\n")

# ---- Solve system of equations using inverse method ----
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

coeff = np.array([
    [2, -3,  1],
    [1, -1,  2],
    [3,  1, -1]
])

const = np.array([-1, -3, 9])

# Solve using inverse: X = inv(A) @ B
solution_inv = np.linalg.inv(coeff) @ const
print("Solution using inverse:", solution_inv)

# Solve using np.linalg.solve (more stable)
solution_solve = np.linalg.solve(coeff, const)
print("Solution using solve:", solution_solve)


1) A @ inv(A):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]] 

2) AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB == BA ? False 

3) (AB)^T:
 [[23 51]
 [13 29]]
   B^T A^T:
 [[23 51]
 [13 29]]
   Equal ? True 

Solution using inverse: [ 2.  1. -2.]
Solution using solve: [ 2.  1. -2.]


Problem 4.2: How Fast is NumPy?

In [6]:
# Problem 4.2: How Fast is NumPy?

size = 1_000_000

# Python lists
L1 = list(range(size))
L2 = list(range(size))

# NumPy arrays
A1 = np.arange(size)
A2 = np.arange(size)

# 1) Element-wise Addition
start = time.time()
list_add = [L1[i] + L2[i] for i in range(size)]
list_t_add = time.time() - start

start = time.time()
numpy_add = A1 + A2
numpy_t_add = time.time() - start

print("1) Addition:")
print("Python:", list_t_add)
print("NumPy :", numpy_t_add, "\n")

# 2) Multiplication
start = time.time()
list_mul = [L1[i] * L2[i] for i in range(size)]
list_t_mul = time.time() - start

start = time.time()
numpy_mul = A1 * A2
numpy_t_mul = time.time() - start

print("2) Multiplication:")
print("Python:", list_t_mul)
print("NumPy :", numpy_t_mul, "\n")

# 3) Dot Product
start = time.time()
list_dot = sum(L1[i] * L2[i] for i in range(size))
list_t_dot = time.time() - start

start = time.time()
numpy_dot = np.dot(A1, A2)
numpy_t_dot = time.time() - start

print("3) Dot Product:")
print("Python:", list_t_dot)
print("NumPy :", numpy_t_dot, "\n")

# 4) Matrix Multiplication 1000x1000
mat_size = 1000

# Generate data
M1_list = np.random.random((mat_size, mat_size)).tolist()
M2_list = np.random.random((mat_size, mat_size)).tolist()

# Python matmul
start = time.time()
M2_T = list(zip(*M2_list))
M_result = [[sum(a*b for a,b in zip(row,col)) for col in M2_T] for row in M1_list]
list_t_mat = time.time() - start

# NumPy matmul
M1_np = np.array(M1_list)
M2_np = np.array(M2_list)

start = time.time()
M_np_res = M1_np @ M2_np
numpy_t_mat = time.time() - start

print("4) Matrix Multiplication:")
print("Python:", list_t_mat)
print("NumPy :", numpy_t_mat)


1) Addition:
Python: 0.11909174919128418
NumPy : 0.004974365234375 

2) Multiplication:
Python: 0.11693644523620605
NumPy : 0.005751848220825195 

3) Dot Product:
Python: 0.1261138916015625
NumPy : 0.0022881031036376953 

4) Matrix Multiplication:
Python: 121.05290627479553
NumPy : 0.06757187843322754
